/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all users
         * @description Get all users without pagination
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Get all users */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: cuid */
                            id: string;
                            name: string;
                            username: string;
                            email: string;
                            avatarURL: string | null;
                            createdAt: string | null;
                            updatedAt: string | null;
                        }[];
                    };
                };
                /** @description Failed to get all users */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user details
         * @description Get a user by username, email, or id.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    username: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: cuid */
                            id: string;
                            name: string;
                            username: string;
                            email: string;
                            avatarURL: string | null;
                            createdAt: string | null;
                            updatedAt: string | null;
                        };
                    };
                };
                /** @description User not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to get user */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all cities
         * @description Get a list of cities.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cities retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: cuid */
                            id: string;
                            slug: string;
                            name: string;
                            latitude: number;
                            longitude: number;
                            createdAt: string | null;
                            updatedAt: string | null;
                        }[];
                    };
                };
                /** @description Failed to retrieve cities */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cities/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get city details
         * @description Get a city by slug or id.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description City retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: cuid */
                            id: string;
                            slug: string;
                            name: string;
                            latitude: number;
                            longitude: number;
                            createdAt: string | null;
                            updatedAt: string | null;
                        };
                    };
                };
                /** @description City not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to retrieve city */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register user
         * @description Register a new user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        username: string;
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description User registered successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            user: {
                                /** Format: cuid */
                                id: string;
                                name: string;
                                username: string;
                                email: string;
                                avatarURL: string | null;
                                createdAt: string | null;
                                updatedAt: string | null;
                            };
                        };
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to register user */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login user
         * @description Login user by email or username.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description identifier: email | username */
                        identifier: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description User logged in successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            user: {
                                /** Format: cuid */
                                id: string;
                                name: string;
                                username: string;
                                email: string;
                                avatarURL: string | null;
                                createdAt: string | null;
                                updatedAt: string | null;
                            };
                            token: string;
                        };
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid email or password */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to login user */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get authenticated user
         * @description Get authenticated user information.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User information retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            user: {
                                /** Format: cuid */
                                id: string;
                                name: string;
                                username: string;
                                email: string;
                                avatarURL: string | null;
                                createdAt: string | null;
                                updatedAt: string | null;
                            };
                        };
                    };
                };
                /** @description Invalid token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to retrieve user information */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all places
         * @description Get a list of places.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Places retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: cuid */
                            id: string;
                            slug: string;
                            name: string;
                            description: string | null;
                            priceMin: string;
                            priceMax: string;
                            cityId: string;
                            address: string;
                            latitude: number;
                            longitude: number;
                            userId: string;
                            createdAt: string | null;
                            updatedAt: string | null;
                            images: string[];
                        }[];
                    };
                };
                /** @description Failed to retrieve places */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Create a place
         * @description Add a new place.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        description?: string;
                        priceMin: number;
                        priceMax: number;
                        city: string;
                        address: string;
                        latitude: number;
                        longitude: number;
                    };
                };
            };
            responses: {
                /** @description Place created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            place: {
                                /** Format: cuid */
                                id: string;
                                slug: string;
                                name: string;
                                description: string | null;
                                priceMin: string;
                                priceMax: string;
                                cityId: string;
                                address: string;
                                latitude: number;
                                longitude: number;
                                userId: string;
                                createdAt: string | null;
                                updatedAt: string | null;
                            };
                        };
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to create place */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/places/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get place details
         * @description Get place details by slug or id.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Place retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: cuid */
                            id: string;
                            slug: string;
                            name: string;
                            description: string | null;
                            priceMin: unknown;
                            priceMax: unknown;
                            cityId: string;
                            address: string;
                            latitude: number;
                            longitude: number;
                            userId: string;
                            createdAt: string | null;
                            updatedAt: string | null;
                            menuItems: {
                                /** Format: cuid */
                                id: string;
                                slug: string;
                                name: string;
                                price: unknown;
                                description: string | null;
                                placeId: string;
                                userId: string;
                                createdAt: string | null;
                                updatedAt: string | null;
                                images: string[];
                            }[];
                        };
                    };
                };
                /** @description Place not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to retrieve place */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a place
         * @description Delete a place by slug or id.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Place deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            place: {
                                /** Format: cuid */
                                id: string;
                                slug: string;
                                name: string;
                                description: string | null;
                                priceMin: string;
                                priceMax: string;
                                cityId: string;
                                address: string;
                                latitude: number;
                                longitude: number;
                                userId: string;
                                createdAt: string | null;
                                updatedAt: string | null;
                            };
                        };
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Place not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to delete place */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a place
         * @description Update a place by slug or id.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                        description?: string;
                        priceMin?: number;
                        priceMax?: number;
                        city?: string;
                        address?: string;
                        latitude?: number;
                        longitude?: number;
                    };
                };
            };
            responses: {
                /** @description Place updated successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            place: {
                                /** Format: cuid */
                                id: string;
                                slug: string;
                                name: string;
                                description: string | null;
                                priceMin: string;
                                priceMax: string;
                                cityId: string;
                                address: string;
                                latitude: number;
                                longitude: number;
                                userId: string;
                                createdAt: string | null;
                                updatedAt: string | null;
                            };
                        };
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Place not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to update place */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/menu-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all menu items
         * @description Get a list of menu items.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Menu items retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: cuid */
                            id: string;
                            slug: string;
                            name: string;
                            price: string;
                            description: string | null;
                            placeId: string;
                            userId: string;
                            createdAt: string | null;
                            updatedAt: string | null;
                        }[];
                    };
                };
                /** @description Failed to retrieve menu items */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Create a menu item
         * @description Add a new menu item.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        price: number;
                        description?: string;
                        images: {
                            url: string;
                        }[];
                        placeSlug: string;
                    };
                };
            };
            responses: {
                /** @description Menu item created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            menuItem: {
                                /** Format: cuid */
                                id: string;
                                slug: string;
                                name: string;
                                price: string;
                                description: string | null;
                                placeId: string;
                                userId: string;
                                createdAt: string | null;
                                updatedAt: string | null;
                            };
                        };
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Place not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to create menu item */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/menu-items/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a menu item
         * @description Get a menu item by slug or id.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Menu item retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: cuid */
                            id: string;
                            slug: string;
                            name: string;
                            price: string;
                            description: string | null;
                            placeId: string;
                            userId: string;
                            createdAt: string | null;
                            updatedAt: string | null;
                        };
                    };
                };
                /** @description Menu item not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to retrieve menu item */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete a menu item
         * @description Delete a menu item by slug.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Menu item deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            menuItem: {
                                /** Format: cuid */
                                id: string;
                                slug: string;
                                name: string;
                                price: string;
                                description: string | null;
                                placeId: string;
                                userId: string;
                                createdAt: string | null;
                                updatedAt: string | null;
                            };
                        };
                    };
                };
                /** @description Menu item not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to delete menu item */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a menu item
         * @description Update a menu item by slug.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                        price?: number;
                        description?: string | null;
                        images?: {
                            url: string;
                        }[];
                        placeSlug?: string;
                    };
                };
            };
            responses: {
                /** @description Menu item updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            menuItem: {
                                /** Format: cuid */
                                id: string;
                                slug: string;
                                name: string;
                                price: string;
                                description: string | null;
                                placeId: string;
                                userId: string;
                                createdAt: string | null;
                                updatedAt: string | null;
                            };
                        };
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Menu item not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to update menu item */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/menu-items/{slug}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get menu item reviews
         * @description Get all reviews on a menu item by slug.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Menu item reviews retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: cuid */
                            id: string;
                            menuItemId: string;
                            userId: string;
                            rating: number;
                            comment: string | null;
                            createdAt: string | null;
                            updatedAt: string | null;
                        }[];
                    };
                };
                /** @description Menu item reviews not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to retrieve menu item reviews */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Add a menu item review
         * @description Add a new menu item review.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        rating: number;
                        comment?: string;
                    };
                };
            };
            responses: {
                /** @description Menu item review created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            menuItemReview: {
                                /** Format: cuid */
                                id: string;
                                menuItemId: string;
                                userId: string;
                                rating: number;
                                comment: string | null;
                                createdAt: string | null;
                                updatedAt: string | null;
                            };
                        };
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Menu item not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to create menu item review */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Delete a menu item review
         * @description Delete a menu item review by username and menu slug.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Menu item review deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            menuItemReview: {
                                /** Format: cuid */
                                id: string;
                                menuItemId: string;
                                userId: string;
                                rating: number;
                                comment: string | null;
                                createdAt: string | null;
                                updatedAt: string | null;
                            };
                        };
                    };
                };
                /** @description Menu item review not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to delete menu item review */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a menu item review
         * @description Update a menu item review by username and slug.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        rating?: number;
                        comment?: string;
                    };
                };
            };
            responses: {
                /** @description Menu item review updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            message: string;
                            menuItemReview: {
                                /** Format: cuid */
                                id: string;
                                menuItemId: string;
                                userId: string;
                                rating: number;
                                comment: string | null;
                                createdAt: string | null;
                                updatedAt: string | null;
                            };
                        };
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Menu item review not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to update menu item review */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Search places and menu items by keyword. */
        get: {
            parameters: {
                query: {
                    q: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Search results */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            places: {
                                /** Format: cuid */
                                id: string;
                                slug: string;
                                name: string;
                                description: string | null;
                                priceMin: string;
                                priceMax: string;
                                cityId: string;
                                address: string;
                                latitude: number;
                                longitude: number;
                                userId: string;
                                createdAt: string | null;
                                updatedAt: string | null;
                                images: string[];
                            }[];
                            menuItems: {
                                /** Format: cuid */
                                id: string;
                                slug: string;
                                name: string;
                                price: string;
                                description: string | null;
                                placeId: string;
                                userId: string;
                                createdAt: string | null;
                                updatedAt: string | null;
                                place: {
                                    /** Format: cuid */
                                    id: string;
                                    slug: string;
                                    name: string;
                                    description: string | null;
                                    priceMin: string;
                                    priceMax: string;
                                    cityId: string;
                                    address: string;
                                    latitude: number;
                                    longitude: number;
                                    userId: string;
                                    createdAt: string | null;
                                    updatedAt: string | null;
                                };
                            }[];
                        };
                    };
                };
                /** @description Failed to search */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to search */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
